window:
  title: Terminal

font:
  normal:
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux/BSD) monospace
    #   - (Windows) Consolas
    family: Fira Code

  size: 11.0

cursor:
  style:
    # Cursor shape
    #
    # Values for `shape`:
    #   - ▇ Block
    #   - _ Underline
    #   - | Beam
    shape: Block

    # Cursor blinking state
    #
    # Values for `blinking`:
    #   - Never: Prevent the cursor from ever blinking
    #   - Off: Disable blinking by default
    #   - On: Enable blinking by default
    #   - Always: Force the cursor to always blink
    blinking: On

  # Cursor blinking interval in milliseconds.
  blink_interval: 500

# Colors (Poimandres)
colors:
  # Default colors
  primary:
    background: "0x1b1e28"
    foreground: "0xa6accd"

  # Cursor colors
  cursor:
    text: "0xa6accd"
    cursor: "0xa6accd"

  # Search colors
  #
  # Colors used for the search bar and match highlighting.
  search:
    # Allowed values are CellForeground/CellBackground, which reference the
    # affected cell, or hexadecimal colors like #ff00ff.
    matches:
      foreground: "0x1b1e28"
      background: "0xadd7ff"

    focused_match:
      foreground: "0x1b1e28"
      background: "0xadd7ff"

    bar:
      foreground: "0x1b1e28"
      background: "0xadd7ff"

  # Selection colors
  #
  # Colors which should be used to draw the selection area.
  #
  # Allowed values are CellForeground/CellBackground, which reference the
  # affected cell, or hexadecimal colors like #ff00ff.
  selection:
    text: CellForeground
    background: "0x303340"

  # Vi mode cursor colors
  #
  # Colors for the cursor when the vi mode is active.
  #
  # Allowed values are CellForeground/CellBackground, which reference the
  # affected cell, or hexadecimal colors like #ff00ff.
  vi_mode_cursor:
    text: CellBackground
    cursor: CellForeground

  # Normal colors
  normal:
    black: "0x1b1e28"
    red: "0xd0679d"
    green: "0x5de4c7"
    yellow: "0xfffac2"
    blue: "0x89ddff"
    magenta: "0xfcc5e9"
    cyan: "0xadd7ff"
    white: "0xffffff"

  # Bright colors
  bright:
    black: "0xa6accd"
    red: "0xd0679d"
    green: "0x5de4c7"
    yellow: "0xfffac2"
    blue: "0xadd7ff"
    magenta: "0xfae4fc"
    cyan: "0x89ddff"
    white: "0xffffff"
