{
  imports = [
    ./1password
    ./bat
    ./beekeeper-studio
    ./chromium
    ./docker
    ./finder
    ./kubectx
    ./node
    ./openscad
    ./parallels
    ./python
    ./safari
    ./wezterm
    ./zed

    ./any-nix-shell.nix
    ./aws.nix
    ./bun.nix
    ./claude.nix
    ./delta.nix
    ./devenv.nix
    ./direnv.nix
    ./fd.nix
    ./flameshot.nix
    ./forgit.nix
    ./git.nix
    ./kubectl.nix
    ./kubelogin.nix
    ./nix-index.nix
    ./nixfmt.nix
    ./obsidian.nix
    ./openspec.nix
    ./oxfmt.nix
    ./rustup.nix
    ./shfmt.nix
    ./stylua.nix
    ./terraform.nix
    ./up.nix
    ./vim.nix
    ./watchman.nix
  ];
}
