{
  imports = [
    ./1password
    ./aws
    ./bat
    ./chrome
    ./direnv
    ./fnm
    ./helix
    ./kubectl
    ./kubectx
    ./openscad
    ./vim
    ./vscode
    ./wezterm
    ./zoxide

    ./any-nix-shell.nix
    ./bash.nix
    ./black.nix
    ./delta.nix
    ./devenv.nix
    ./docker.nix
    ./expo.nix
    ./fd.nix
    ./fish.nix
    ./flameshot.nix
    ./forgit.nix
    ./fzf.nix
    ./git.nix
    ./kubelogin.nix
    ./lazygit.nix
    ./nix-index.nix
    ./nixpkgs-fmt.nix
    ./obsidian.nix
    ./prettier.nix
    ./python.nix
    ./rustup.nix
    ./shfmt.nix
    ./starship.nix
    ./stylua.nix
    ./terraform.nix
    ./up.nix
    ./watchman.nix
  ];
}
